name: Python Tests

on:
  push:
    branches: [ main, break-build-* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.9

    - name: Display Python version
      run: uv run python --version

    - name: Run tests with verbose output
      run: |
        uv run python -m unittest CalcTest.py -v

    - name: Run tests with simple output
      if: always()
      run: |
        uv run python CalcTest.py
